files:
  - source: Example.xliff
    translation: /%original_path%/%two_letters_code%.%original_file_name%
  - source: /src/main/locales/*.json
    translation: /src/main/locales/%two_letters_code%.*.json
