files:
  - source: /src/**/Example (iOS Strings).strings
    translation: /src/**/%two_letters_code%.%file_name%.strings
  - source: /src/**/Example (AndroidXML).xml
    translation: /src/**/%two_letters_code%/%file_name%.xml
