files:
  - source: /src/main/locales/Example 1.json
    translation: /src/main/locales/%two_letters_code%.Example 1.json
  - source: /**/*.md
    translation: /**/%two_letters_code%.COPY.md
bundles:
  - 8
