files:
  - source: /src/**/Example 1.json
    translation: /src/main/locales/%two_letters_code%.%file_name%.json
  - source: /src/main/locales/*.xml
    translation: /src/main/locales/%two_letters_code%.%file_extension%.xml
