files:
  - source: /**/Example 1.json
    translation: /src/main/locales/%two_letters_code%.%file_name%.json
  - source: /**/Generic FormatJS.json
    translation: /**/%two_letters_code%.%file_name%.json
